# Generated by Django 2.2.4 on 2022-01-04 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='chat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=400)),
                ('patterns', models.CharField(max_length=5000)),
                ('responses', models.CharField(max_length=5000)),
            ],
        ),
    ]
