# Generated by Django 2.2.4 on 2022-01-13 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='bot_user',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=80)),
                ('user_res', models.CharField(max_length=50000)),
                ('bot_res', models.CharField(max_length=50000)),
            ],
        ),
    ]
