# Generated by Django 2.2.4 on 2021-12-21 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('choach', '0002_services'),
    ]

    operations = [
        migrations.AlterField(
            model_name='services',
            name='image',
            field=models.FileField(default='', upload_to='service'),
        ),
    ]
