# Generated by Django 2.2.4 on 2022-02-18 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('choach', '0003_auto_20211221_1132'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.CharField(default='empty', max_length=100)),
                ('no', models.CharField(default='empty', max_length=20)),
                ('msg', models.CharField(default='empty', max_length=2000)),
            ],
        ),
    ]
