# Generated by Django 2.2.4 on 2022-04-13 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('choach', '0005_subscribe'),
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('image', models.FileField(default='', upload_to='service')),
                ('paragraph1', models.CharField(default='empty', max_length=2000)),
                ('paragraph2', models.CharField(default='empty', max_length=2000)),
                ('paragraph3', models.CharField(default='empty', max_length=2000)),
            ],
        ),
        migrations.CreateModel(
            name='Programs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('image', models.FileField(default='', upload_to='blog')),
                ('paragraph1', models.CharField(default='empty', max_length=2000)),
                ('paragraph2', models.CharField(default='empty', max_length=2000)),
                ('paragraph3', models.CharField(default='empty', max_length=2000)),
            ],
        ),
    ]
